### PR TITLE
"Defaukt" and "ProductPPage" typos have been corrected as "Default" and "ProductPage".

### PR DESCRIPTION
**Pull request by OpenSoftware-World**
"Defaukt" and "ProductPPage" typos have been corrected as "Default" and "ProductPage".

### CODE REVIEW

**Comment by ardatdev** [comment]
Did you test it? Because changing them might cause different issues.

**Comment by LinuxUsersLinuxMint** [comment]
> Did you test it? Because changing them might cause different issues.

No I didn't test it. However, my aim was to show the spelling mistake, you can do this by testing if you wish.

**Comment by LinuxUsersLinuxMint** [comment]
> Did you test it? Because changing them might cause different issues.

Okay, now I have reviewed the files I edited again and I don't think it will cause any problems. The pull request is safe now. @ardatdev @Arnolxu

**Comment by Arnolxu** [comment]
There are some other files that use that wrong names, you need to find and change them too so we can merge this. It's OK if you don't feel like doing it, I can do it when I'm free.

Here's the Powershell command I used to use for searching text in all files, which may help you: `Get-ChildItem -Recurse | Select-String 'string to search' -List | Select Path`

**Comment by LinuxUsersLinuxMint** [comment]
> There are some other files that use that wrong names, you need to find and change them too so we can merge this. It's OK if you don't feel like doing it, I can do it when I'm free.
> 
> Here's the Powershell command I used to use for searching text in all files, which may help you: `Get-ChildItem -Recurse | Select-String 'string to search' -List | Select Path`

Okay, I will deal with it as soon as possible, but I will postpone this process until the midterm break, so I request that nothing be done to this pull request for now.

**Pull request closed without merging**
