### PR TITLE
Artado Search Rewrite

### PR DESCRIPTION
**Pull request by yasinldev**
The basis of Artado Search has been changed and the transition from ASP.NET to TypeScript / React has been made, as well as more different features have been added and made ready for use. The current pull request is still being developed and when it comes out of the beta process, it will be merge and replace the current version on [artadosearch.com.](https://artadosearch.com/)

### CODE REVIEW

**Review by ardatdev — COMMENTED** [review]
nice.

**Comment by ardatdev** [comment]
I don't think we need a changelog page. Because we already share our updates on our forum.

**Comment by yasinldev** [comment]
uh oki 👍

**Comment by ardatdev** [comment]
I think we should delete Contributors page. It doesn't really makes sense to keep and we can't deal with updating it all the time. Also there are some people that has nothing to do with Artado in the page.

**Comment by ardatdev** [comment]
Also the Artado Manifesto is not about a search engine or its principles. The original manifesto doesn't even mention a search engine. Because we are not just a company or an organization that only develops a search engine. We have other projects too. Artado is not just a search engine. Thus our manifesto is not about a search engine's principles. Artado Manifesto is about anti-censorship and freedom. Artado Manifesto tells how we can build a better internet for everyone. Artado Manifesto tells the reason why Artado exists.

**Pull request closed without merging**
